server:
  port: 5000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  mqtt:
    #MQTT??????????1883????????????
    url: tcp://127.0.0.1:1883
    #???
    username: admin
    #??
    password: liu0929pan0.
    #???id(????)
    client:
      id: consumer-1
    #MQTT?????????????????????
    default:
      topic: topic