server:
  port: 5000

logging:
  config: classpath:logback-spring.xml
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  mqtt:
    url: tcp://172.16.24.111:1883
    username:
    password:
    client:
      id: consumer-1
    default:
      topic: topic
  datasource:
    url: jdbc:mysql://172.16.24.111:3306/application?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: fengtaiSec.666
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      idle-timeout: 10000
      connection-test-query: select 1
      connection-timeout: 30000
      pool-name: hikariCP
  redis:
    host: 172.16.24.111
    port: 6379
    password: 123456